### ISSUE TITLE
Crashes: App crashed on pressing refresh icon in home

### ISSUE THREAD

**Issue by hereyubaraj** [naxadeve/MNE-Android#22]
First time in installation app is getting crashed after pressing refresh icon. Need to show the cluster list without clicking refresh button as well.

**Crash log screenshot**

<img width="1331" alt="Screenshot 2019-04-10 10 50 33" src="https://user-images.githubusercontent.com/47551530/55852987-d93a6300-5b7e-11e9-940f-c240b2aca8d0.png">

**Comment by konishon** [comment]
I was not able to reproduce this issue
